name       : lldb
version    : 9.0.0
release    : 4
source     :
    - http://releases.llvm.org/9.0.0/lldb-9.0.0.src.tar.xz : 1e4c2f6a1f153f4b8afa2470d2e99dab493034c1ba8b7ffbbd7600de016d0794
license    : NCSA
component  : programming.tools
summary    : High performance debugger, part of the LLVM project.
description: |
    LLDB is a next generation, high-performance debugger. It is built as a set of reusable components which highly leverage existing libraries in the larger LLVM Project, such as the Clang expression parser and LLVM disassembler.
clang      : yes
builddeps  :
    - pkgconfig(libedit)
    - swig
rundeps    :
    - python-six
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-python-path-as-python-still-in-lib-directory.patch
    %cmake_ninja \
        -DLLDB_USE_SYSTEM_SIX=ON \
        -DLLVM_LINK_LLVM_DYLIB=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %python_compile
