name       : lldb
version    : 13.0.0
release    : 13
source     :
    - https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/lldb-13.0.0.src.tar.xz : 24c65bd5ec0d7cbc37bafdd7533b1783352708bf6338c403a72f47884e406dbd
license    : NCSA
component  : programming.tools
summary    : High performance debugger, part of the LLVM project.
description: |
    LLDB is a next generation, high-performance debugger. It is built as a set of reusable components which highly leverage existing libraries in the larger LLVM Project, such as the Clang expression parser and LLVM disassembler.
clang      : yes
libsplit   : no
builddeps  :
    - pkgconfig(libedit)
    - pkgconfig(python3)
    - swig
rundeps    :
    - python-six
setup      : |
    %cmake_ninja \
        -DLLDB_USE_SYSTEM_SIX=ON \
        -DLLVM_LINK_LLVM_DYLIB=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %python3_compile
