name       : lldb
version    : 8.0.1
release    : 3
source     :
    - https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/lldb-8.0.1.src.tar.xz : e8a79baa6d11dd0650ab4a1b479f699dfad82af627cbbcd49fa6f2dc14e131d7
license    : NCSA
component  : programming.tools
summary    : High performance debugger, part of the LLVM project.
description: |
    LLDB is a next generation, high-performance debugger. It is built as a set of reusable components which highly leverage existing libraries in the larger LLVM Project, such as the Clang expression parser and LLVM disassembler.
clang      : yes
builddeps  :
    - pkgconfig(libedit)
    - swig
rundeps    :
    - python-six
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-python-path-as-python-still-in-lib-directory.patch
    %cmake_ninja \
        -DLLDB_USE_SYSTEM_SIX=ON \
        -DLLVM_LINK_LLVM_DYLIB=ON \
        -DPYTHON_EXECUTABLE=/usr/bin/python2 \
        -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so \
        -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 \
        -DLLDB_LIBDIR_SUFFIX=""
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Relocate lldb python's custom readline.so module which links agaisnt libedit
    mv "$installdir"/usr/lib64/python2.7/site-packages/{,lldb/}readline.so
    sed -i '2isys.path.insert(1, "/usr/lib64/python2.7/site-packages/lldb")' \
    "$installdir/usr/lib64/python2.7/site-packages/lldb/embedded_interpreter.py"

    %python_compile
